/**
 * Core module exports for numpy-ts
 */

export {
  type DTypeName,
  type TypedArray,
  type TypedArrayConstructor,
  type DTypeToTypedArray,
  type DTypeToElement,
  type NumericDTypeName,
  type DTypeDescriptor,
  DType,
  dtypes,
  getDTypeDescriptor,
  isValidDTypeName,
  inferDType,
  inferDTypeFromArray,
  promoteDTypes,
  canCast,
  DEFAULT_DTYPE,
} from './dtype.js';

export {
  type Shape,
  type MutableShape,
  validateShape,
  shapeToSize,
  shapeToNdim,
  shapesEqual,
  normalizeShape,
  inferShape,
  validateDataShape,
  flattenData,
  transposeShape,
  permuteShape,
  normalizeAxis,
  normalizeAxes,
  getReducedShape,
  getSqueezeShape,
  getExpandDimsShape,
  getConcatShape,
  getStackShape,
} from './shape.js';

export {
  type Strides,
  type MutableStrides,
  type Order,
  calculateStrides,
  calculateStridesC,
  calculateStridesF,
  indicesToOffset,
  offsetToIndices,
  isCContiguous,
  isFContiguous,
  isContiguous,
  stridesEqual,
  transposeStrides,
  permuteStrides,
  broadcastStrides,
  reshapeStrides,
  sliceStrides,
  expandDimsStrides,
  squeezeStrides,
} from './strides.js';

export {
  type BroadcastResult,
  type BroadcastMapping,
  areBroadcastable,
  areAllBroadcastable,
  broadcastTwoShapes,
  broadcastShapes,
  getBroadcastInfo,
  getBroadcastMapping,
  getBroadcastStrides,
  BroadcastIterator,
  mapBroadcastIndex,
  broadcastIndexToOffset,
  needsBroadcast,
  getBroadcastAxes,
} from './broadcasting.js';

export {
  type SliceSpec,
  type DimensionIndex,
  type IndexSpec,
  type IndexResult,
  slice,
  parseSliceString,
  normalizeIndex,
  normalizeSlice,
  isScalarIndex,
  isSliceIndex,
  normalizeDimensionIndex,
  applyIndex,
  getSliceIndices,
  parseIndexSpec,
  IndexIterator,
  indicesToFlat,
  flatToIndices,
  validateIndices,
  applyFancyIndex,
  applyBooleanMask,
  selectAxis,
} from './indexing.js';

export {
  type NDArrayOptions,
  type ArrayInput,
  NDArray,
} from './ndarray.js';
